### ISSUE TITLE
Make it possible to add a link to provide Room Developer credentials on a link

### ISSUE THREAD

**Issue by pavittr** [gameontext/interactivemap#2]
@ebullient and I discussed the idea of being able to provide a link in the /play/me section of GameOn that linked directly to the Interactive Map, but pre-populated the Room Developer Credentials. 

To avoid making the parameters visible, the suggestion was to use an SSL POST request and set the GameOn ID and GameOn Secret in the body of the request.

**Comment by ebullient** [comment]
optional. I think there may be other ways to make registration easier... 

"Nice to have" for JavaOne

**Comment by ebullient** [comment]
I prefer new registration behavior in the main UI.
